name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  ci:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26
          cache: false
      - name: Install dependencies
        run: go get .
      - name: Build binary
        run: go build .
      - name: Run tests
        run: go test -v ./...
